In [1]:
from producecfg import *
from libSOGA import *

from time import time

# Bernoulli

true value: 0.25

In [2]:
start = time()
cfg = produce_cfg('Bernoulli')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0070841312408447266


In [3]:
cfg.ID_list

['theta', 'y']

In [4]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 30 total: 12.284345626831055
Updates: 42 total: 0.04745078086853027
Mergings: 11 total: 0.0
Time for changing coordinates: 3.1386525630950928 	Time for moments computation: 8.28840160369873
Computation completed in  12.498433589935303
N. components: 1774


array([0.25191365, 1.        ])

### Pruning

In [5]:
start = time()
cfg = produce_cfg('BernoulliPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [6]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 30 total: 1.8985142707824707
Updates: 42 total: 0.03230142593383789
Mergings: 21 total: 2.4241533279418945
Time for changing coordinates: 0.620356559753418 	Time for moments computation: 1.1804165840148926
Computation completed in  4.356967449188232
N. components: 43


array([0.25191376, 1.        ])

# CoinBias

true value: 0.417

In [7]:
start = time()
cfg = produce_cfg('CoinBias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.014291524887084961


In [8]:
cfg.ID_list

['bias', 'y']

In [9]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 15 total: 0.3416616916656494
Updates: 22 total: 0.015645980834960938
Mergings: 6 total: 0.0
Time for changing coordinates: 0.08611178398132324 	Time for moments computation: 0.20855069160461426
Computation completed in  0.3885538578033447
N. components: 64


array([0.41545796, 0.        ])

### Pruning

In [10]:
start = time()
cfg = produce_cfg('CoinBiasPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [11]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 15 total: 0.22803306579589844
Updates: 22 total: 0.0
Mergings: 11 total: 0.04706406593322754
Time for changing coordinates: 0.0667581558227539 	Time for moments computation: 0.12840962409973145
Computation completed in  0.2810368537902832
N. components: 11


array([0.41545809, 0.        ])

# Burglar

exact

In [12]:
start = time()
cfg = produce_cfg('Burglar')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01556253433227539


In [13]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Truncations: 15 total: 0.0
Updates: 16 total: 0.015514373779296875
Mergings: 8 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.015514373779296875
N. components: 4


0.0029934492413055433

# MurderMistery

exact

In [14]:
start = time()
cfg = produce_cfg('MurderMistery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [15]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 3 total: 0.0
Updates: 3 total: 0.0
Mergings: 2 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.0
N. components: 2


array([0.01581722, 1.        ])

# Digit

true value ?

In [16]:
start = time()
cfg = produce_cfg('DigitRecognition')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.1562366485595703


In [17]:
cfg.ID_list[:10]

['y', 'dig']

In [18]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)

output_dist.gm.mean()[0]

Truncations: 3020 total: 3.437730073928833
Updates: 4030 total: 0.39076662063598633
Mergings: 1011 total: 0.015615701675415039
Time for changing coordinates: 0.7020642757415771 	Time for moments computation: 1.001018762588501
Computation completed in  4.11077880859375


4.4539341842632565

# Grass

exact

In [19]:
start = time()
cfg = produce_cfg('Grass')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015580415725708008


In [20]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Truncations: 19 total: 0.01563858985900879
Updates: 24 total: 0.0
Mergings: 10 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.0467984676361084
N. components: 28


0.7079276773296245

# NoisyOr

exact

In [21]:
start = time()
cfg = produce_cfg('NoisyOr')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015714168548583984


In [22]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Truncations: 18 total: 0.01564764976501465
Updates: 24 total: 0.08853673934936523
Mergings: 10 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.12000465393066406
N. components: 256


0.8144187499999991

### Pruning

(makes computational time longer)

In [23]:
start = time()
cfg = produce_cfg('NoisyOrPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.022556066513061523


In [24]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Truncations: 18 total: 0.047681331634521484
Updates: 24 total: 0.04691433906555176
Mergings: 11 total: 0.9723913669586182
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  1.082719087600708
N. components: 10


0.8144187499999999

# SurveyUnbias

true value: 0.8

In [25]:
start = time()
cfg = produce_cfg('SurveyUnbias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.00948190689086914


In [26]:
cfg.ID_list

['bias1', 'bias2', 'ansb1', 'ansb2']

In [27]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 15 total: 1.1850557327270508
Updates: 24 total: 0.0
Mergings: 6 total: 0.0
Time for changing coordinates: 0.3931550979614258 	Time for moments computation: 0.7528963088989258
Computation completed in  1.1850557327270508
N. components: 128


0.7987653829530976

### Pruning

In [28]:
start = time()
cfg = produce_cfg('SurveyUnbiasPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [29]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 15 total: 0.21910333633422852
Updates: 24 total: 0.0
Mergings: 11 total: 0.04703259468078613
Time for changing coordinates: 0.015576839447021484 	Time for moments computation: 0.20352649688720703
Computation completed in  0.26613593101501465
N. components: 5


0.7986450321840382

# TrueSkill

true value: 0.843

In [30]:
start = time()
cfg = produce_cfg('TrueSkill')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [31]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 4 total: 0.09380269050598145
Updates: 9 total: 0.0
Mergings: 2 total: 0.0
Time for changing coordinates: 0.015588521957397461 	Time for moments computation: 0.07821416854858398
Computation completed in  0.09380269050598145
N. components: 2


array([104.7131717 ,  97.60989161,  97.67693972, 115.31779335,
        92.23214662,  92.45005544,   0.85297923])

# TwoCoins

exact

In [32]:
start = time()
cfg = produce_cfg('TwoCoins')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [33]:
cfg.ID_list

['first', 'second', 'both']

In [34]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 5 total: 0.0
Updates: 6 total: 0.0
Mergings: 3 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.0
N. components: 3


array([0.33333333, 0.33333333, 0.        ])

# BayesPointMachine

true value: 0.056

In [2]:
start = time()
cfg = produce_cfg('BayesPointMachine')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.028211116790771484


In [3]:
cfg.ID_list

['w[0]',
 'w[1]',
 'w[2]',
 'mean[0]',
 'mean[1]',
 'mean[2]',
 'mean[3]',
 'mean[4]',
 'mean[5]',
 'res[0]',
 'res[1]',
 'res[2]',
 'res[3]',
 'res[4]',
 'res[5]']

In [4]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

mean = output_dist.gm.mean()

Truncations: 6 total: 439.3736228942871
Updates: 17 total: 0.022998332977294922
Mergings: 1 total: 0.0
Time for changing coordinates: 0.005194902420043945 	Time for moments computation: 439.3664348125458
Computation completed in  439.4010353088379
N. components: 1


In [5]:
mean[0]

0.011565553955733776

# ClickGraph

true value: 0.614154

In [6]:
cfg = produce_cfg('ClickGraph')

In [7]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']

In [8]:
## goes timeout > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [9]:
cfg = produce_cfg('ClickGraphPrune')

In [10]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 50 total: 188.44921851158142
Updates: 57 total: 0.06349849700927734
Mergings: 41 total: 4.233009099960327
Time for changing coordinates: 1.2714338302612305 	Time for moments computation: 186.9067621231079
Computation completed in  192.793803691864
N. components: 26


0.6342728638405396

# ClinicalTrial2

true value: 0.754902

In [11]:
cfg = produce_cfg('ClinicalTrial2')

In [12]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [13]:
# goes time out > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [14]:
cfg = produce_cfg('ClinicalTrial2Prune')

In [15]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [16]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 32 total: 56.869590520858765
Updates: 46 total: 0.0030052661895751953
Mergings: 23 total: 0.2082054615020752
Time for changing coordinates: 0.21808362007141113 	Time for moments computation: 56.57679104804993
Computation completed in  57.09851408004761
N. components: 11


0.7531745870842527

# Indian GPA

true value: 1

In [17]:
start = time()
cfg = produce_cfg('IndianGPA')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.00958251953125


In [18]:
cfg.ID_list

['usa', 'usagpa', 'indgpa', 'gpa']

In [19]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Truncations: 7 total: 0.06341290473937988
Updates: 7 total: 0.011106729507446289
Mergings: 4 total: 0.0
Time for changing coordinates: 0.03141903877258301 	Time for moments computation: 0.01964855194091797
Computation completed in  0.07559347152709961
N. components: 11


array([1.        , 4.        , 5.12034045, 4.        ])

# Gauss Examples

## BernoulliGauss

In [20]:
start = time()
cfg = produce_cfg('Gauss/BernoulliGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.005084514617919922


In [21]:
cfg.ID_list

['theta', 'y']

In [22]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 30 total: 0.05494880676269531
Updates: 42 total: 0.0050525665283203125
Mergings: 11 total: 0.0
Time for changing coordinates: 0.008093833923339844 	Time for moments computation: 0.03130173683166504
Computation completed in  0.06604170799255371
N. components: 1


-0.7532570956172188

## CoinBiasGauss

In [23]:
start = time()
cfg = produce_cfg('Gauss/CoinBiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0012049674987792969


In [24]:
cfg.ID_list

['theta', 'y']

In [25]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 15 total: 0.021817684173583984
Updates: 22 total: 0.012140512466430664
Mergings: 6 total: 0.0
Time for changing coordinates: 0.0009996891021728516 	Time for moments computation: 0.005242586135864258
Computation completed in  0.03395819664001465
N. components: 1


0.19787983308028412

## SurveyUnbiasGauss

In [26]:
start = time()
cfg = produce_cfg('Gauss/SurveyUnbiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.004160404205322266


In [27]:
cfg.ID_list

['bias1', 'bias2', 'yb1', 'yb2']

In [28]:
start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 15 total: 0.024689435958862305
Updates: 24 total: 0.014512300491333008
Mergings: 6 total: 0.0
Time for changing coordinates: 0.0028624534606933594 	Time for moments computation: 0.004006385803222656
Computation completed in  0.0429081916809082
N. components: 1


1.5303404369003732

## ClickGraphGauss

In [29]:
start = time()
cfg = produce_cfg('Gauss/ClickGraphGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01775050163269043


In [30]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'y0', 'y1']

In [31]:
times = []

start = time()
output_dist = start_SOGA(cfg)
end = time()
    
print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 50 total: 64.2243275642395
Updates: 57 total: 0.01863574981689453
Mergings: 21 total: 0.0
Time for changing coordinates: 0.18227076530456543 	Time for moments computation: 63.9790358543396
Computation completed in  64.2429633140564
N. components: 32


0.8955243258596454

## ClinicalTrialGauss

In [32]:
start = time()
cfg = produce_cfg('Gauss/ClinicalTrialGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.014759063720703125


In [33]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [34]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Truncations: 32 total: 3.1407275199890137
Updates: 46 total: 0.005289554595947266
Mergings: 12 total: 0.0
Time for changing coordinates: 0.0041773319244384766 	Time for moments computation: 3.1224584579467773
Computation completed in  3.1471080780029297
N. components: 2


0.7612237232813578

# AQUA Example

## Altermu

true value: 
mu1: 3.365363543395006e-16
mu2: 3.365363543395006e-16
mu3: -0.11221539502189211

In [35]:
start = time()
cfg = produce_cfg('AQUA/Altermu')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.013580083847045898


In [36]:
cfg.ID_list

['y[0]',
 'y[1]',
 'y[2]',
 'y[3]',
 'y[4]',
 'y[5]',
 'y[6]',
 'y[7]',
 'y[8]',
 'y[9]',
 'y[10]',
 'y[11]',
 'y[12]',
 'y[13]',
 'y[14]',
 'y[15]',
 'y[16]',
 'y[17]',
 'y[18]',
 'y[19]',
 'y[20]',
 'y[21]',
 'y[22]',
 'y[23]',
 'y[24]',
 'y[25]',
 'y[26]',
 'y[27]',
 'y[28]',
 'y[29]',
 'y[30]',
 'y[31]',
 'y[32]',
 'y[33]',
 'y[34]',
 'y[35]',
 'y[36]',
 'y[37]',
 'y[38]',
 'y[39]',
 'w1',
 'w2',
 'w3',
 'mean']

In [37]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-4:-1]

Truncations: 40 total: 0.031445980072021484
Updates: 127 total: 0.0894467830657959
Mergings: 1 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.14187097549438477
N. components: 1


array([ 0.        ,  0.        , -0.00137427], dtype=float32)

## Altermu2

true value:
mu1:  0.15521420874071362
mu2:  0.1552142087407135

In [38]:
start = time()
cfg = produce_cfg('AQUA/Altermu2')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0052111148834228516


In [39]:
cfg.ID_list

['y[0]',
 'y[1]',
 'y[2]',
 'y[3]',
 'y[4]',
 'y[5]',
 'y[6]',
 'y[7]',
 'y[8]',
 'y[9]',
 'y[10]',
 'y[11]',
 'y[12]',
 'y[13]',
 'y[14]',
 'y[15]',
 'y[16]',
 'y[17]',
 'y[18]',
 'y[19]',
 'y[20]',
 'y[21]',
 'y[22]',
 'y[23]',
 'y[24]',
 'y[25]',
 'y[26]',
 'y[27]',
 'y[28]',
 'y[29]',
 'y[30]',
 'y[31]',
 'y[32]',
 'y[33]',
 'y[34]',
 'y[35]',
 'y[36]',
 'y[37]',
 'y[38]',
 'y[39]',
 'w1',
 'w2']

In [40]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-2:]

Truncations: 40 total: 0.12838387489318848
Updates: 124 total: 0.1936025619506836
Mergings: 1 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.33086133003234863
N. components: 4


array([0.15558612, 0.15558612], dtype=float32)

## Normal Mixtures

In [41]:
start = time()
cfg = produce_cfg('AQUA/NormalMixture')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.008028030395507812


In [42]:
# goes t.o. > 30 min even with pruning

# times = []
# 
# start = time()
# output_dist = start_SOGA(cfg)
# end = time()
# times.append(end-start)
# 
# print('Computation completed in ', np.mean(times))
# 
# output_dist.gm.mean()

## TimeSeries

true value 
alpha:  -1.5751952024094684
beta:  0.6841150519335847
lambda:  0.4765771501058374

In [43]:
start = time()
cfg = produce_cfg('AQUA/TimeSeries')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.07837605476379395


In [44]:
cfg.ID_list

['a',
 'b',
 'lamb',
 'y0',
 'y1',
 'y2',
 'y3',
 'y4',
 'y5',
 'y6',
 'y7',
 'y8',
 'y9',
 'y10',
 'y11',
 'y12',
 'y13',
 'y14',
 'y15',
 'y16',
 'y17',
 'y18',
 'y19',
 'y20',
 'y21',
 'y22',
 'y23',
 'y24',
 'y25',
 'y26',
 'y27',
 'y28',
 'y29',
 'y30',
 'y31',
 'y32',
 'y33',
 'y34',
 'y35',
 'y36',
 'y37',
 'y38',
 'y39']

In [45]:
start = time()
output_dist = start_SOGA(cfg)
end = time()

print('Computation completed in ', end-start)
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[:3]

Truncations: 39 total: 0.2044086456298828
Updates: 121 total: 0.7229657173156738
Mergings: 1 total: 0.0
Time for changing coordinates: 0 	Time for moments computation: 0
Computation completed in  0.9599003791809082
N. components: 8


array([-1.6015656,  0.695174 ,  0.4535055], dtype=float32)