In [1]:
from producecfg import *
from libSOGA import *

from time import time

# Bernoulli

true value: 0.25

In [2]:
start = time()
cfg = produce_cfg('Bernoulli')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.020444393157958984


In [3]:
cfg.ID_list

['theta', 'y']

In [4]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  10.440170073509217
N. components: 1774


array([0.25191365, 1.        ])

### Pruning

In [5]:
start = time()
cfg = produce_cfg('BernoulliPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.007208824157714844


In [6]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  3.8949867486953735
N. components: 43


array([0.25191376, 1.        ])

# CoinBias

true value: 0.417

In [7]:
start = time()
cfg = produce_cfg('CoinBias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.004755496978759766


In [8]:
cfg.ID_list

['bias', 'y']

In [9]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.40234951972961425
N. components: 64


array([0.41545796, 0.        ])

### Pruning

In [10]:
start = time()
cfg = produce_cfg('CoinBiasPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.012921571731567383


In [11]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.33314855098724366
N. components: 11


array([0.41545809, 0.        ])

# Burglar

exact

In [12]:
start = time()
cfg = produce_cfg('Burglar')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.004756450653076172


In [13]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Computation completed in  0.18146200180053712
N. components: 4


0.0029934492413055433

# MurderMistery

exact

In [14]:
start = time()
cfg = produce_cfg('MurderMistery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.003997802734375


In [15]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.019902420043945313
N. components: 2


array([0.01581722, 1.        ])

# Digit

true value ?

In [5]:
start = time()
cfg = produce_cfg('DigitRecognition')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.18636322021484375


In [6]:
cfg.ID_list[:10]

['y', 'dig']

In [7]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))

output_dist.gm.mean()[0]

Computation completed in  22.836566066741945


4.4539341842632565

In [8]:
output_dist.gm.n_comp()

10

# Grass

exact

In [19]:
start = time()
cfg = produce_cfg('Grass')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01950836181640625


In [20]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))

output_dist.gm.mean()[1]

Computation completed in  0.4887106418609619


0.7079276773296245

# NoisyOr

exact

In [21]:
start = time()
cfg = produce_cfg('NoisyOr')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.017378807067871094


In [22]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.6974511861801147
N. components: 256


0.8144187499999991

### Pruning

(makes computational time longer)

In [23]:
start = time()
cfg = produce_cfg('NoisyOrPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.011020898818969727


In [24]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  1.7147482872009276
N. components: 10


0.8144187499999999

# SurveyUnbias

true value: 0.8

In [25]:
start = time()
cfg = produce_cfg('SurveyUnbias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.008361339569091797


In [26]:
cfg.ID_list

['bias1', 'bias2', 'ansb1', 'ansb2']

In [27]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.8471679449081421
N. components: 128


0.7987653829530976

### Pruning

In [28]:
start = time()
cfg = produce_cfg('SurveyUnbiasPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.007689714431762695


In [29]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.31405518054962156
N. components: 5


0.7986450321840382

# TrueSkill

true value: 0.843

In [30]:
start = time()
cfg = produce_cfg('TrueSkill')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006744861602783203


In [31]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.09642543792724609
N. components: 2


array([104.7131717 ,  97.60989161,  97.67693972, 115.31779335,
        92.23214662,  92.45005544,   0.85297923])

# TwoCoins

exact

In [32]:
start = time()
cfg = produce_cfg('TwoCoins')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [33]:
cfg.ID_list

['first', 'second', 'both']

In [34]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.032881879806518556
N. components: 3


array([0.33333333, 0.33333333, 0.        ])

# BayesPointMachine

true value: 0.056

In [35]:
start = time()
cfg = produce_cfg('BayesPointMachine')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015389204025268555


In [36]:
cfg.ID_list

['w[0]',
 'w[1]',
 'w[2]',
 'mean[0]',
 'mean[1]',
 'mean[2]',
 'mean[3]',
 'mean[4]',
 'mean[5]']

In [37]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

mean = output_dist.gm.mean()

Computation completed in  2.336533045768738
N. components: 1


In [38]:
mean[0]

0.01117729116231203

# ClickGraph

true value: 0.614154

In [39]:
cfg = produce_cfg('ClickGraph')

In [40]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']

In [41]:
## goes timeout > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [42]:
cfg = produce_cfg('ClickGraphPrune')

In [43]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  106.34841470718384
N. components: 26


0.6342728638405396

# ClinicalTrial2

true value: 0.754902

In [44]:
cfg = produce_cfg('ClinicalTrial2')

In [45]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [46]:
# goes time out > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [47]:
cfg = produce_cfg('ClinicalTrial2Prune')

In [48]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [49]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  28.26886022090912
N. components: 11


0.7531745870842527

# Indian GPA

true value: 1

In [50]:
start = time()
cfg = produce_cfg('IndianGPA')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006972551345825195


In [51]:
cfg.ID_list

['usa', 'usagpa', 'indgpa', 'gpa']

In [52]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.18957395553588868
N. components: 11


array([1.        , 4.        , 5.12034045, 4.        ])

# Gauss Examples

## BernoulliGauss

In [53]:
start = time()
cfg = produce_cfg('Gauss/BernoulliGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [54]:
cfg.ID_list

['theta', 'y']

In [55]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.1563183069229126
N. components: 1


-0.7532570956172188

## CoinBiasGauss

In [56]:
start = time()
cfg = produce_cfg('Gauss/CoinBiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [57]:
cfg.ID_list

['theta', 'y']

In [58]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.07662029266357422
N. components: 1


0.19787983308028412

## SurveyUnbiasGauss

In [59]:
start = time()
cfg = produce_cfg('Gauss/SurveyUnbiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015636682510375977


In [60]:
cfg.ID_list

['bias1', 'bias2', 'yb1', 'yb2']

In [61]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.08162922859191894
N. components: 1


1.5303404369003732

## ClickGraphGauss

In [62]:
start = time()
cfg = produce_cfg('Gauss/ClickGraphGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01536107063293457


In [63]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'y0', 'y1']

In [64]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  31.84140775203705
N. components: 32


0.8955243258596454

## ClinicalTrialGauss

In [65]:
start = time()
cfg = produce_cfg('Gauss/ClinicalTrialGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.008198976516723633


In [66]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [67]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  3.4365038156509398
N. components: 2


0.7612237232813578

# AQUA Example

## Altermu

true value: 
mu1: 3.365363543395006e-16
mu2: 3.365363543395006e-16
mu3: -0.11221539502189211

In [68]:
start = time()
cfg = produce_cfg('AQUA/Altermu')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.019553184509277344


In [69]:
cfg.ID_list

['y[0]',
 'y[1]',
 'y[2]',
 'y[3]',
 'y[4]',
 'y[5]',
 'y[6]',
 'y[7]',
 'y[8]',
 'y[9]',
 'y[10]',
 'y[11]',
 'y[12]',
 'y[13]',
 'y[14]',
 'y[15]',
 'y[16]',
 'y[17]',
 'y[18]',
 'y[19]',
 'y[20]',
 'y[21]',
 'y[22]',
 'y[23]',
 'y[24]',
 'y[25]',
 'y[26]',
 'y[27]',
 'y[28]',
 'y[29]',
 'y[30]',
 'y[31]',
 'y[32]',
 'y[33]',
 'y[34]',
 'y[35]',
 'y[36]',
 'y[37]',
 'y[38]',
 'y[39]',
 'w1',
 'w2',
 'w3',
 'mean']

In [70]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-4:-1]

Computation completed in  0.23090050220489503
N. components: 1


array([ 0.        ,  0.        , -0.00137427], dtype=float32)

## Altermu2

true value:
mu1:  0.15521420874071362
mu2:  0.1552142087407135

In [71]:
start = time()
cfg = produce_cfg('AQUA/Altermu2')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0040056705474853516


In [72]:
cfg.ID_list

['y[0]',
 'y[1]',
 'y[2]',
 'y[3]',
 'y[4]',
 'y[5]',
 'y[6]',
 'y[7]',
 'y[8]',
 'y[9]',
 'y[10]',
 'y[11]',
 'y[12]',
 'y[13]',
 'y[14]',
 'y[15]',
 'y[16]',
 'y[17]',
 'y[18]',
 'y[19]',
 'y[20]',
 'y[21]',
 'y[22]',
 'y[23]',
 'y[24]',
 'y[25]',
 'y[26]',
 'y[27]',
 'y[28]',
 'y[29]',
 'y[30]',
 'y[31]',
 'y[32]',
 'y[33]',
 'y[34]',
 'y[35]',
 'y[36]',
 'y[37]',
 'y[38]',
 'y[39]',
 'w1',
 'w2']

In [73]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-2:]

Computation completed in  0.5876893281936646
N. components: 4


array([0.15558612, 0.15558612], dtype=float32)

## Normal Mixtures

In [74]:
start = time()
cfg = produce_cfg('AQUA/NormalMixture')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.04372096061706543


In [75]:
## goes t.o. > 30 min even with pruning
#
#times = []
#
#start = time()
#output_dist = start_SOGA(cfg)
#end = time()
#times.append(end-start)
#
#print('Computation completed in ', np.mean(times))
#
#output_dist.gm.mean()

## TimeSeries

true value 
alpha:  -1.5751952024094684
beta:  0.6841150519335847
lambda:  0.4765771501058374

In [79]:
start = time()
cfg = produce_cfg('AQUA/TimeSeries')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.15778350830078125


In [80]:
cfg.ID_list

['a',
 'b',
 'lamb',
 'y0',
 'y1',
 'y2',
 'y3',
 'y4',
 'y5',
 'y6',
 'y7',
 'y8',
 'y9',
 'y10',
 'y11',
 'y12',
 'y13',
 'y14',
 'y15',
 'y16',
 'y17',
 'y18',
 'y19',
 'y20',
 'y21',
 'y22',
 'y23',
 'y24',
 'y25',
 'y26',
 'y27',
 'y28',
 'y29',
 'y30',
 'y31',
 'y32',
 'y33',
 'y34',
 'y35',
 'y36',
 'y37',
 'y38',
 'y39']

In [81]:
times = []

for i in range(10):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[:3]

Computation completed in  1.8969426155090332
N. components: 8


array([-1.6015656,  0.695174 ,  0.4535055], dtype=float32)