In [1]:
from producecfg import *
from libSOGA import *

from time import time

num_rep = 1

# Bernoulli

true value: 0.25

In [2]:
start = time()
cfg = produce_cfg('Bernoulli')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02380537986755371


In [3]:
cfg.ID_list

['theta', 'y']

In [4]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  10.684901475906372
N. components: 1774


array([0.25191365, 1.        ])

### Pruning

In [5]:
start = time()
cfg = produce_cfg('BernoulliPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006986379623413086


In [6]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  1.2667100429534912
N. components: 27


array([0.25191323, 1.        ])

In [7]:
0.015*1774

26.61

# BayesPointMachine

true value: 0.056

In [8]:
start = time()
cfg = produce_cfg('BayesPointMachine')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02199864387512207


In [9]:
cfg.ID_list

['w[0]',
 'w[1]',
 'w[2]',
 'mean[0]',
 'mean[1]',
 'mean[2]',
 'mean[3]',
 'mean[4]',
 'mean[5]']

In [10]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

mean = output_dist.gm.mean()

Computation completed in  1.975945234298706
N. components: 1


In [11]:
mean[0]

0.01117729116231203

# Burglar

exact

In [12]:
start = time()
cfg = produce_cfg('Burglar')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.025007963180541992


In [13]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['earthquake', 'burglary', 'alarm', 'phoneWorking', 'maryWakes', 'called']
#vars: 6


In [14]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Computation completed in  0.06257081031799316
N. components: 4


0.0029934492413055433

# ClickGraph

true value: 0.614154

In [15]:
start = time()
cfg = produce_cfg('ClickGraph')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.018749713897705078


In [16]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']
#vars: 6


In [17]:
# goes timeout > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [18]:
start = time()
cfg = produce_cfg('ClickGraphPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.019000530242919922


In [19]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']

In [20]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  211.00355219841003
N. components: 35


0.6296009102280258

In [21]:
0.015*2304

34.56

# ClinicalTrial2

true value: 0.754902

In [22]:
cfg = produce_cfg('ClinicalTrial2')

In [23]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']
#vars: 5


In [24]:
# goes time out > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [25]:
start = time()
cfg = produce_cfg('ClinicalTrial2Prune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.009576559066772461


In [26]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [27]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  85.56371688842773
N. components: 23


0.7530902888328648

In [28]:
0.015*1508

22.619999999999997

# CoinBias

true value: 0.417

In [29]:
start = time()
cfg = produce_cfg('CoinBias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.008089542388916016


In [30]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['bias', 'y']
#vars: 2


In [31]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.41928744316101074
N. components: 64


array([0.41545796, 0.        ])

### Pruning

In [32]:
#start = time()
#cfg = produce_cfg('CoinBiasPrune')
#end = time()
#
#print('Time to produce cfg: ', end-start)

In [33]:
#times = []
#
#for i in range(10):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()

# Digit

true value ?

In [34]:
start = time()
cfg = produce_cfg('DigitRecognition')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.14428329467773438


In [35]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y', 'dig']
#vars: 2


In [36]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))

output_dist.gm.mean()[0]

Computation completed in  4.527403831481934


4.4539341842632565

In [37]:
output_dist.gm.n_comp()

10

# Grass

exact

In [38]:
start = time()
cfg = produce_cfg('Grass')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.039354562759399414


In [39]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['cloudy', 'rain', 'sprinkler', 'temp1', 'wetRoof', 'temp2', 'temp3', 'or1', 'or2', 'wetGrass']
#vars: 10


In [40]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Computation completed in  0.07657814025878906
N. components: 28


0.7079276773296245

In [41]:
509/719

0.7079276773296245

# MurderMistery

exact

In [42]:
start = time()
cfg = produce_cfg('MurderMistery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.003998756408691406


In [43]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['aliceDunnit', 'withGun']
#vars: 2


In [44]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.006005287170410156
N. components: 2


array([0.01581722, 1.        ])

# NoisyOr

exact

In [45]:
start = time()
cfg = produce_cfg('NoisyOr')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.024994850158691406


In [46]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['n0', 'n4', 'n1', 'n21', 'n22', 'n33', 'n2', 'n31', 'n32', 'n3']
#vars: 10


In [47]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.14866328239440918
N. components: 256


0.8144187499999991

### Pruning

(makes computational time longer)

In [48]:
#start = time()
#cfg = produce_cfg('NoisyOrPrune')
#end = time()
#
#print('Time to produce cfg: ', end-start)

In [49]:
#times = []
#
#for i in range(1):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()[-1]

# SurveyUnbias

true value: 0.8

In [50]:
start = time()
cfg = produce_cfg('SurveyUnbias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.010732650756835938


In [51]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['bias1', 'bias2', 'ansb1', 'ansb2']
#vars: 4


In [52]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  1.4238173961639404
N. components: 128


0.7987653829530976

### Pruning

In [53]:
#start = time()
#cfg = produce_cfg('SurveyUnbiasPrune')
#end = time()
#
#print('Time to produce cfg: ', end-start)

In [54]:
#times = []
#
#for i in range(10):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()[0]

# TrueSkill

true value: 0.843

In [55]:
start = time()
cfg = produce_cfg('TrueSkill')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.007092714309692383


In [56]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['skillA', 'skillB', 'skillC', 'perfA', 'perfB', 'perfC']
#vars: 6


In [57]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.041570186614990234
N. components: 1


array([104.71317347,  97.6098938 ,  97.67694092, 115.3177955 ,
        92.23214722,  92.45005919])

# TwoCoins

exact

In [58]:
start = time()
cfg = produce_cfg('TwoCoins')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.010553598403930664


In [59]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['first', 'second', 'both']
#vars: 3


In [60]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.0059969425201416016
N. components: 3


array([0.33333333, 0.33333333, 0.        ])

# Indian GPA

true value: 1

In [61]:
start = time()
cfg = produce_cfg('IndianGPA')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [62]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['usa', 'usagpa', 'indgpa', 'gpa']
#vars: 4


In [63]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.09995508193969727
N. components: 11


array([1.        , 4.        , 5.12034045, 4.        ])

# AQUA Example

## Altermu

true value: 
mu1: 3.365363543395006e-16
mu2: 3.365363543395006e-16
mu3: -0.11221539502189211

In [64]:
start = time()
cfg = produce_cfg('AQUA/Altermu')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.013909339904785156


In [65]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'w1', 'w2', 'w3', 'mean']
#vars: 44


In [66]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-4:-1]

Computation completed in  0.10061097145080566
N. components: 1


array([ 0.        ,  0.        , -0.00137427], dtype=float32)

## Altermu2

true value:
mu1:  0.15521420874071362
mu2:  0.1552142087407135

In [67]:
start = time()
cfg = produce_cfg('AQUA/Altermu2')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.007154703140258789


In [68]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'w1', 'w2']
#vars: 42


In [69]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-2:]

Computation completed in  0.2515997886657715
N. components: 4


array([0.15558612, 0.15558612], dtype=float32)

## Normal Mixtures

In [70]:
start = time()
cfg = produce_cfg('AQUA/NormalMixture')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015401840209960938


In [71]:
# goes t.o. > 30 min even with pruning

#times = []
#
#start = time()
#output_dist = start_SOGA(cfg)
#end = time()
#times.append(end-start)
#
#print('Computation completed in ', np.mean(times))
#
#output_dist.gm.mean()

### Pruning

In [72]:
start = time()
cfg = produce_cfg('AQUA/NormalMixturePrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.012998580932617188


In [73]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['theta', 'mu1', 'mu2', 'y']
#vars: 4


In [74]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))

output_dist.gm.mean()

Computation completed in  46.39567852020264


array([ 0.2982786,  3.6915321,  4.8735046, 10.624819 ], dtype=float32)

In [75]:
output_dist.gm.n_comp()

30

In [76]:
30/97714

0.00030701844157439054

## RadarQuery

In [77]:
start = time()
cfg = produce_cfg('AQUA/RadarQuery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015180349349975586


In [78]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['b0', 'b1', 'x0', 'x1', 'x', 'y', 'o0', 'o1']
#vars: 8


In [79]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  6.060856580734253
N. components: 2016


array([ 0.9999916 ,  0.9999916 ,  5.940395  ,  5.940395  , -1.6595752 ,
        0.33188623,  4.999984  ,  4.6127315 ], dtype=float32)

### Pruning

In [80]:
start = time()
cfg = produce_cfg('AQUA/RadarQueryPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.05713200569152832


In [81]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  3.6446430683135986
N. components: 16


array([ 1.        ,  1.        ,  5.6110787 ,  5.6110787 , -1.5685694 ,
        0.33188942,  5.        ,  4.374827  ], dtype=float32)

In [82]:
0.015*2016

30.24

## TimeSeries

true value 
alpha:  -1.5751952024094684
beta:  0.6841150519335847
lambda:  0.4765771501058374

In [80]:
start = time()
cfg = produce_cfg('AQUA/TimeSeries')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.1035776138305664


In [81]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['a', 'b', 'lamb', 'y0', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'y8', 'y9', 'y10', 'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19', 'y20', 'y21', 'y22', 'y23', 'y24', 'y25', 'y26', 'y27', 'y28', 'y29', 'y30', 'y31', 'y32', 'y33', 'y34', 'y35', 'y36', 'y37', 'y38', 'y39']
#vars: 43


In [82]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[:3]

Computation completed in  0.8542513847351074
N. components: 8


array([-1.6015656,  0.695174 ,  0.4535055], dtype=float32)

# Gauss Examples

## BernoulliGauss

In [86]:
start = time()
cfg = produce_cfg('Gauss/BernoulliGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [87]:
cfg.ID_list

['theta', 'y']

In [88]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.06399154663085938
N. components: 1


-0.7532570956172188

## ClickGraphGauss

In [89]:
start = time()
cfg = produce_cfg('Gauss/ClickGraphGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01399683952331543


In [90]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'y0', 'y1']

In [91]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  62.69479584693909
N. components: 32


0.8955243258596454

## ClinicalTrialGauss

In [92]:
start = time()
cfg = produce_cfg('Gauss/ClinicalTrialGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.016111135482788086


In [93]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [94]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  13.271811246871948
N. components: 2


0.7612237232813578

## CoinBiasGauss

In [95]:
start = time()
cfg = produce_cfg('Gauss/CoinBiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006535530090332031


In [96]:
cfg.ID_list

['theta', 'y']

In [97]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.04008221626281738
N. components: 1


0.19787983308028412

## SurveyUnbiasGauss

In [98]:
start = time()
cfg = produce_cfg('Gauss/SurveyUnbiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0162353515625


In [99]:
cfg.ID_list

['bias1', 'bias2', 'yb1', 'yb2']

In [100]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.04799342155456543
N. components: 1


1.5303404369003732

## ExpGauss

In [101]:
start = time()
cfg = produce_cfg('Gauss/Exponential')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [102]:
cfg.ID_list

['expon', 'norm', 'res']

In [103]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.01764369010925293
N. components: 3


array([ 1.14813365, 10.02380349, 11.50223372])

## LaplaceGauss

In [104]:
start = time()
cfg = produce_cfg('Gauss/Laplace')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [105]:
cfg.ID_list

['lap', 'mean', 'res']

In [106]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.008020162582397461
N. components: 2


array([0.79427045, 0.52436254, 1.31863306])

## Altermu2Gauss

In [107]:
start = time()
cfg = produce_cfg('Gauss/Altermu2Gauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.008016347885131836


In [108]:
cfg.ID_list

['y[0]',
 'y[1]',
 'y[2]',
 'y[3]',
 'y[4]',
 'y[5]',
 'y[6]',
 'y[7]',
 'y[8]',
 'y[9]',
 'y[10]',
 'y[11]',
 'y[12]',
 'y[13]',
 'y[14]',
 'y[15]',
 'y[16]',
 'y[17]',
 'y[18]',
 'y[19]',
 'y[20]',
 'y[21]',
 'y[22]',
 'y[23]',
 'y[24]',
 'y[25]',
 'y[26]',
 'y[27]',
 'y[28]',
 'y[29]',
 'y[30]',
 'y[31]',
 'y[32]',
 'y[33]',
 'y[34]',
 'y[35]',
 'y[36]',
 'y[37]',
 'y[38]',
 'y[39]',
 'w1',
 'w2']

In [109]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-2]

Computation completed in  0.17656993865966797
N. components: 1


-9.844197

## NormalMixturesGauss

In [110]:
start = time()
cfg = produce_cfg('Gauss/NormalMixtureGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.00803828239440918


In [111]:
cfg.ID_list

['theta', 'mu1', 'mu2', 'y']

In [112]:
#times = []
#
#for i in range(1):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()

## RadarGauss

In [113]:
start = time()
cfg = produce_cfg('Gauss/RadarQueryGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02400827407836914


In [114]:
cfg.ID_list

['b0', 'b1', 'x0', 'x1', 'x', 'y', 'o0', 'o1']

In [115]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.06441450119018555
N. components: 4


array([ 0.99999994,  0.99999994,  5.9664793 ,  5.9664793 , -1.7839675 ,
        0.79776406,  5.        ,  4.6128087 ], dtype=float32)

## TimeSeries Gauss

In [116]:
start = time()
cfg = produce_cfg('Gauss/TimeSeriesGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.08841180801391602


In [117]:
cfg.ID_list

['a',
 'b',
 'lamb',
 'y0',
 'y1',
 'y2',
 'y3',
 'y4',
 'y5',
 'y6',
 'y7',
 'y8',
 'y9',
 'y10',
 'y11',
 'y12',
 'y13',
 'y14',
 'y15',
 'y16',
 'y17',
 'y18',
 'y19',
 'y20',
 'y21',
 'y22',
 'y23',
 'y24',
 'y25',
 'y26',
 'y27',
 'y28',
 'y29',
 'y30',
 'y31',
 'y32',
 'y33',
 'y34',
 'y35',
 'y36',
 'y37',
 'y38',
 'y39']

In [118]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.19240713119506836
N. components: 1


array([-2.3806071 ,  0.638875  ,  0.15277529, -1.0907003 , -2.4951322 ,
       -2.079189  , -3.3462107 , -3.2190576 , -3.8483515 , -4.145916  ,
       -2.170857  , -2.72986   , -2.3541741 , -3.0579832 , -2.853604  ,
       -2.9261494 , -2.6771345 , -2.9773197 , -4.75105   , -3.2939904 ,
       -4.1162605 , -4.080864  , -3.347433  , -3.5929496 , -1.7048937 ,
       -3.5229118 , -4.1394463 , -4.049923  , -3.717073  , -2.6830206 ,
       -3.2192028 , -1.7822183 , -1.7138561 , -3.1528468 , -3.2609491 ,
       -2.9224002 , -2.4018636 , -3.1697333 , -4.0054073 , -2.3262532 ,
       -1.7482764 , -1.0571622 , -3.4453678 ], dtype=float32)