In [1]:
from producecfg import *
from libSOGA import *

from time import time

num_rep = 10

# Bernoulli

true value: 0.25

In [2]:
start = time()
cfg = produce_cfg('Bernoulli')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0199892520904541


In [3]:
cfg.ID_list

['theta', 'y']

In [4]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  11.821075820922852
N. components: 1774


array([0.25191365, 1.        ])

### Pruning

In [5]:
start = time()
cfg = produce_cfg('BernoulliPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.007999897003173828


In [6]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  1.3080849409103394
N. components: 27


array([0.25191323, 1.        ])

In [7]:
0.015*1774

26.61

# BayesPointMachine

true value: 0.056

In [8]:
start = time()
cfg = produce_cfg('BayesPointMachine')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.029430150985717773


In [9]:
cfg.ID_list

['w[0]',
 'w[1]',
 'w[2]',
 'mean[0]',
 'mean[1]',
 'mean[2]',
 'mean[3]',
 'mean[4]',
 'mean[5]']

In [10]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

mean = output_dist.gm.mean()

Computation completed in  1.996245265007019
N. components: 1


In [11]:
mean[0]

0.01117729116231203

# Burglar

exact

In [12]:
start = time()
cfg = produce_cfg('Burglar')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.021674394607543945


In [13]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['earthquake', 'burglary', 'alarm', 'phoneWorking', 'maryWakes', 'called']
#vars: 6


In [14]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Computation completed in  0.01907618045806885
N. components: 4


0.0029934492413055433

# ClickGraph

true value: 0.614154

In [15]:
start = time()
cfg = produce_cfg('ClickGraph')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.014531850814819336


In [16]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']
#vars: 6


In [17]:
# goes timeout > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [18]:
start = time()
cfg = produce_cfg('ClickGraphPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.018636465072631836


In [19]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']

In [20]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  210.3988070487976
N. components: 35


0.6296009102280258

In [21]:
0.015*2304

34.56

# ClinicalTrial2

true value: 0.754902

In [22]:
cfg = produce_cfg('ClinicalTrial2')

In [23]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']
#vars: 5


In [24]:
# goes time out > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [25]:
start = time()
cfg = produce_cfg('ClinicalTrial2Prune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.003994464874267578


In [26]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [27]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  89.6955958366394
N. components: 23


0.7530902888328648

In [28]:
0.015*1508

22.619999999999997

# CoinBias

true value: 0.417

In [29]:
start = time()
cfg = produce_cfg('CoinBias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [30]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['bias', 'y']
#vars: 2


In [31]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.4172470808029175
N. components: 64


array([0.41545796, 0.        ])

### Pruning

In [32]:
#start = time()
#cfg = produce_cfg('CoinBiasPrune')
#end = time()
#
#print('Time to produce cfg: ', end-start)

In [33]:
#times = []
#
#for i in range(10):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()

# Digit

true value ?

In [34]:
start = time()
cfg = produce_cfg('DigitRecognition')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.1405956745147705


In [35]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y', 'dig']
#vars: 2


In [36]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))

output_dist.gm.mean()[0]

Computation completed in  4.461561775207519


4.4539341842632565

In [37]:
output_dist.gm.n_comp()

10

# Grass

exact

In [38]:
start = time()
cfg = produce_cfg('Grass')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02398514747619629


In [39]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['cloudy', 'rain', 'sprinkler', 'temp1', 'wetRoof', 'temp2', 'temp3', 'or1', 'or2', 'wetGrass']
#vars: 10


In [40]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Computation completed in  0.05146698951721192
N. components: 28


0.7079276773296245

# MurderMistery

exact

In [41]:
start = time()
cfg = produce_cfg('MurderMistery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006098031997680664


In [42]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['aliceDunnit', 'withGun']
#vars: 2


In [43]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.003117656707763672
N. components: 2


array([0.01581722, 1.        ])

# NoisyOr

exact

In [44]:
start = time()
cfg = produce_cfg('NoisyOr')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01564311981201172


In [45]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['n0', 'n4', 'n1', 'n21', 'n22', 'n33', 'n2', 'n31', 'n32', 'n3']
#vars: 10


In [46]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.11738245487213135
N. components: 256


0.8144187499999991

### Pruning

(makes computational time longer)

In [47]:
#start = time()
#cfg = produce_cfg('NoisyOrPrune')
#end = time()
#
#print('Time to produce cfg: ', end-start)

In [48]:
#times = []
#
#for i in range(1):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()[-1]

# SurveyUnbias

true value: 0.8

In [49]:
start = time()
cfg = produce_cfg('SurveyUnbias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [50]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['bias1', 'bias2', 'ansb1', 'ansb2']
#vars: 4


In [51]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  1.2407533407211304
N. components: 128


0.7987653829530976

### Pruning

In [52]:
#start = time()
#cfg = produce_cfg('SurveyUnbiasPrune')
#end = time()
#
#print('Time to produce cfg: ', end-start)

In [53]:
#times = []
#
#for i in range(10):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()[0]

# TrueSkill

true value: 0.843

In [54]:
start = time()
cfg = produce_cfg('TrueSkill')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006056308746337891


In [55]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['skillA', 'skillB', 'skillC', 'perfA', 'perfB', 'perfC']
#vars: 6


In [56]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.036141610145568846
N. components: 1


array([104.71317347,  97.6098938 ,  97.67694092, 115.3177955 ,
        92.23214722,  92.45005919])

# TwoCoins

exact

In [57]:
start = time()
cfg = produce_cfg('TwoCoins')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.003913402557373047


In [58]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['first', 'second', 'both']
#vars: 3


In [59]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.003934335708618164
N. components: 3


array([0.33333333, 0.33333333, 0.        ])

# Indian GPA

true value: 1

In [60]:
start = time()
cfg = produce_cfg('IndianGPA')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0034058094024658203


In [61]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['usa', 'usagpa', 'indgpa', 'gpa']
#vars: 4


In [62]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.07789053916931152
N. components: 11


array([1.        , 4.        , 5.12034045, 4.        ])

# AQUA Example

## Altermu

true value: 
mu1: 3.365363543395006e-16
mu2: 3.365363543395006e-16
mu3: -0.11221539502189211

In [63]:
start = time()
cfg = produce_cfg('AQUA/Altermu')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.004567146301269531


In [64]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'w1', 'w2', 'w3', 'mean']
#vars: 44


In [65]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-4:-1]

Computation completed in  0.13643901348114013
N. components: 1


array([ 0.        ,  0.        , -0.00137427], dtype=float32)

## Altermu2

true value:
mu1:  0.15521420874071362
mu2:  0.1552142087407135

In [66]:
start = time()
cfg = produce_cfg('AQUA/Altermu2')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.003768444061279297


In [67]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'w1', 'w2']
#vars: 42


In [68]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-2:]

Computation completed in  0.31120059490203855
N. components: 4


array([0.15558612, 0.15558612], dtype=float32)

## Normal Mixtures

In [69]:
start = time()
cfg = produce_cfg('AQUA/NormalMixture')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01150965690612793


In [70]:
# goes t.o. > 30 min even with pruning

#times = []
#
#start = time()
#output_dist = start_SOGA(cfg)
#end = time()
#times.append(end-start)
#
#print('Computation completed in ', np.mean(times))
#
#output_dist.gm.mean()

### Pruning

In [71]:
start = time()
cfg = produce_cfg('AQUA/NormalMixturePrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.011236190795898438


In [72]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['theta', 'mu1', 'mu2', 'y']
#vars: 4


In [73]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))

output_dist.gm.mean()

Computation completed in  50.41815297603607


array([ 0.2982786,  3.6915321,  4.8735046, 10.624819 ], dtype=float32)

In [74]:
output_dist.gm.n_comp()

30

In [75]:
30/97714

0.00030701844157439054

## RadarQuery

In [76]:
start = time()
cfg = produce_cfg('AQUA/RadarQuery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01584005355834961


In [77]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['b0', 'b1', 'x0', 'x1', 'x', 'y', 'o0', 'o1']
#vars: 8


In [78]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  6.409933757781983
N. components: 2016


array([ 0.9999916 ,  0.9999916 ,  5.940395  ,  5.940395  , -1.6595752 ,
        0.33188623,  4.999984  ,  4.6127315 ], dtype=float32)

### Pruning

In [79]:
start = time()
cfg = produce_cfg('AQUA/RadarQueryPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.032740116119384766


In [80]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  1.4620190620422364
N. components: 16


array([ 1.        ,  1.        ,  5.6110787 ,  5.6110787 , -1.5685694 ,
        0.33188942,  5.        ,  4.374827  ], dtype=float32)

In [81]:
0.015*2016

30.24

## TimeSeries

true value 
alpha:  -1.5751952024094684
beta:  0.6841150519335847
lambda:  0.4765771501058374

In [82]:
start = time()
cfg = produce_cfg('AQUA/TimeSeries')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.09679865837097168


In [83]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['a', 'b', 'lamb', 'y0', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'y8', 'y9', 'y10', 'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19', 'y20', 'y21', 'y22', 'y23', 'y24', 'y25', 'y26', 'y27', 'y28', 'y29', 'y30', 'y31', 'y32', 'y33', 'y34', 'y35', 'y36', 'y37', 'y38', 'y39']
#vars: 43


In [84]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[:3]

Computation completed in  0.8901869297027588
N. components: 8


array([-1.6015656,  0.695174 ,  0.4535055], dtype=float32)

# Gauss Examples

## BernoulliGauss

In [78]:
start = time()
cfg = produce_cfg('Gauss/BernoulliGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.011004924774169922


In [79]:
cfg.ID_list

['theta', 'y']

In [80]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.06588220596313477
N. components: 1


-0.7532570956172188

## ClickGraphGauss

In [81]:
start = time()
cfg = produce_cfg('Gauss/ClickGraphGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02284693717956543


In [82]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'y0', 'y1']

In [83]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  69.29225778579712
N. components: 32


0.8955243258596454

## ClinicalTrialGauss

In [84]:
start = time()
cfg = produce_cfg('Gauss/ClinicalTrialGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02126455307006836


In [85]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [86]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  3.171574354171753
N. components: 2


0.7612237232813578

## CoinBiasGauss

In [87]:
start = time()
cfg = produce_cfg('Gauss/CoinBiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.012999534606933594


In [88]:
cfg.ID_list

['theta', 'y']

In [89]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.04368233680725098
N. components: 1


0.19787983308028412

## SurveyUnbiasGauss

In [90]:
start = time()
cfg = produce_cfg('Gauss/SurveyUnbiasGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01800060272216797


In [91]:
cfg.ID_list

['bias1', 'bias2', 'yb1', 'yb2']

In [92]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  0.05299973487854004
N. components: 1


1.5303404369003732

## ExpGauss

In [93]:
start = time()
cfg = produce_cfg('Gauss/Exponential')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006001472473144531


In [94]:
cfg.ID_list

['expon', 'norm', 'res']

In [95]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.013998031616210938
N. components: 3


array([ 1.14813365, 10.02380349, 11.50223372])

## LaplaceGauss

In [96]:
start = time()
cfg = produce_cfg('Gauss/Laplace')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.004998683929443359


In [97]:
cfg.ID_list

['lap', 'mean', 'res']

In [98]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.01303410530090332
N. components: 2


array([0.79427045, 0.52436254, 1.31863306])

## Altermu2Gauss

In [99]:
start = time()
cfg = produce_cfg('Gauss/Altermu2Gauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.012006282806396484


In [100]:
cfg.ID_list

['y[0]',
 'y[1]',
 'y[2]',
 'y[3]',
 'y[4]',
 'y[5]',
 'y[6]',
 'y[7]',
 'y[8]',
 'y[9]',
 'y[10]',
 'y[11]',
 'y[12]',
 'y[13]',
 'y[14]',
 'y[15]',
 'y[16]',
 'y[17]',
 'y[18]',
 'y[19]',
 'y[20]',
 'y[21]',
 'y[22]',
 'y[23]',
 'y[24]',
 'y[25]',
 'y[26]',
 'y[27]',
 'y[28]',
 'y[29]',
 'y[30]',
 'y[31]',
 'y[32]',
 'y[33]',
 'y[34]',
 'y[35]',
 'y[36]',
 'y[37]',
 'y[38]',
 'y[39]',
 'w1',
 'w2']

In [101]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-2]

Computation completed in  0.12274360656738281
N. components: 1


-9.844197

## NormalMixturesGauss

In [102]:
start = time()
cfg = produce_cfg('Gauss/NormalMixtureGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.023006916046142578


In [103]:
cfg.ID_list

['theta', 'mu1', 'mu2', 'y']

In [104]:
#times = []
#
#for i in range(1):
#    start = time()
#    output_dist = start_SOGA(cfg)
#    end = time()
#    times.append(end-start)
#    
#print('Computation completed in ', np.mean(times))
#print('N. components:', output_dist.gm.n_comp())
#
#output_dist.gm.mean()

## RadarGauss

In [105]:
start = time()
cfg = produce_cfg('Gauss/RadarQueryGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.032080888748168945


In [106]:
cfg.ID_list

['b0', 'b1', 'x0', 'x1', 'x', 'y', 'o0', 'o1']

In [107]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.060956716537475586
N. components: 4


array([ 0.99999994,  0.99999994,  5.9664793 ,  5.9664793 , -1.7839675 ,
        0.79776406,  5.        ,  4.6128087 ], dtype=float32)

## TimeSeries Gauss

In [108]:
start = time()
cfg = produce_cfg('Gauss/TimeSeriesGauss')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.10160613059997559


In [109]:
cfg.ID_list

['a',
 'b',
 'lamb',
 'y0',
 'y1',
 'y2',
 'y3',
 'y4',
 'y5',
 'y6',
 'y7',
 'y8',
 'y9',
 'y10',
 'y11',
 'y12',
 'y13',
 'y14',
 'y15',
 'y16',
 'y17',
 'y18',
 'y19',
 'y20',
 'y21',
 'y22',
 'y23',
 'y24',
 'y25',
 'y26',
 'y27',
 'y28',
 'y29',
 'y30',
 'y31',
 'y32',
 'y33',
 'y34',
 'y35',
 'y36',
 'y37',
 'y38',
 'y39']

In [110]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.17213821411132812
N. components: 1


array([-2.3806071 ,  0.638875  ,  0.15277529, -1.0907003 , -2.4951322 ,
       -2.079189  , -3.3462107 , -3.2190576 , -3.8483515 , -4.145916  ,
       -2.170857  , -2.72986   , -2.3541741 , -3.0579832 , -2.853604  ,
       -2.9261494 , -2.6771345 , -2.9773197 , -4.75105   , -3.2939904 ,
       -4.1162605 , -4.080864  , -3.347433  , -3.5929496 , -1.7048937 ,
       -3.5229118 , -4.1394463 , -4.049923  , -3.717073  , -2.6830206 ,
       -3.2192028 , -1.7822183 , -1.7138561 , -3.1528468 , -3.2609491 ,
       -2.9224002 , -2.4018636 , -3.1697333 , -4.0054073 , -2.3262532 ,
       -1.7482764 , -1.0571622 , -3.4453678 ], dtype=float32)

# SpikeAndSlab

## Generating Data

In [30]:
from scipy.stats import multivariate_normal as mvnorm
from scipy.stats import norm
from scipy.stats import bernoulli as bern

In [40]:
x = np.around(mvnorm.rvs(mean=np.zeros(9), cov=np.eye(9), size=40),2)
x.transpose()

array([[ 0.29, -0.34,  0.9 , -0.13,  2.16, -0.84,  0.02,  0.09,  1.62,
         1.43, -0.33,  1.06, -0.37,  1.36, -1.13,  0.78,  0.35,  0.23,
        -0.78,  1.61, -2.91, -0.87, -0.44, -1.84, -1.75, -0.45,  1.95,
        -0.99, -0.51,  0.08,  0.75, -0.2 ,  1.39,  0.6 , -0.26, -0.92,
         1.26,  0.71, -2.11,  1.11],
       [ 0.17,  0.11, -0.98,  1.29, -2.17, -0.99,  0.69, -0.31, -0.45,
        -0.33, -0.21,  0.43, -0.76, -0.93,  2.16,  0.4 ,  0.79,  1.49,
         0.76,  0.37,  0.12,  1.07,  1.4 ,  0.14,  0.76,  1.37,  0.1 ,
        -0.05, -1.24, -0.35,  0.33,  0.6 , -0.35,  0.62,  0.36,  0.2 ,
        -0.06, -0.01,  0.35,  0.57],
       [-0.48,  0.27,  0.45,  0.37, -0.13,  0.38,  1.51,  0.56,  0.63,
        -0.5 ,  0.25, -1.05, -0.93, -0.47, -0.42, -0.28,  0.11, -0.76,
         0.81,  1.07,  0.72, -2.66,  0.03,  1.37, -0.29, -0.48, -0.56,
        -0.85,  0.88,  0.85, -0.86,  0.25, -0.34,  0.17, -1.12,  1.09,
        -0.59, -0.21, -0.25,  1.19],
       [ 0.49,  1.03, -0.68,  0.52,  

In [42]:
alphas = [2,2,2,0.2,0.2,0.2,0,0,0]

In [43]:
y = []
for i in range(len(x)):
    y.append(1 + norm.rvs() + np.array(alphas).dot(np.array(x[i])))
    
np.array(y)

array([ 1.45942973, -0.04480512,  3.60566958,  4.99889057,  0.21985146,
       -0.46470414,  7.73594206,  1.03655178,  2.91669336,  3.06439474,
        2.06540694,  1.61315907, -2.56594842,  1.38937506,  3.37299706,
        2.82614589,  1.87025812,  3.48153067,  2.81839129,  6.68506526,
       -2.41082566, -3.57267313,  2.65813843,  0.49169507, -0.13144864,
        3.65874186,  3.93497374, -3.19211798, -0.89805393,  2.4951916 ,
        2.31628358,  3.3623023 ,  0.91502152,  3.92867296, -0.65667622,
       -0.51357204,  3.39616354,  1.01475427, -3.0406564 ,  8.59976102])

In [46]:
start = time()
cfg = produce_cfg('SpikeAndSlab')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.04700446128845215


In [47]:
cfg.ID_list

['delta[0]',
 'delta[1]',
 'delta[2]',
 'delta[3]',
 'delta[4]',
 'delta[5]',
 'delta[6]',
 'delta[7]',
 'delta[8]',
 'alpha[0]',
 'alpha[1]',
 'alpha[2]',
 'alpha[3]',
 'alpha[4]',
 'alpha[5]',
 'alpha[6]',
 'alpha[7]',
 'alpha[8]',
 'y[0]',
 'y[1]',
 'y[2]',
 'y[3]',
 'y[4]',
 'y[5]',
 'y[6]',
 'y[7]',
 'y[8]',
 'y[9]',
 'y[10]',
 'y[11]',
 'y[12]',
 'y[13]',
 'y[14]',
 'y[15]',
 'y[16]',
 'y[17]',
 'y[18]',
 'y[19]',
 'y[20]',
 'y[21]',
 'y[22]',
 'y[23]',
 'y[24]',
 'y[25]',
 'y[26]',
 'y[27]',
 'y[28]',
 'y[29]',
 'y[30]',
 'y[31]',
 'y[32]',
 'y[33]',
 'y[34]',
 'y[35]',
 'y[36]',
 'y[37]',
 'y[38]',
 'y[39]',
 'w']

In [ ]:
times = []

for i in range(1):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()